
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aparna
 */
public class home_page extends javax.swing.JFrame {
private  int count=1;
LinkedHashSet<String> al=new LinkedHashSet<String>();
    /**
     * Creates new form home_page
     */
public void insertTable(){
        if(j3.getText().equals("")){
    JOptionPane.showMessageDialog(this, "enter customer name to insert",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
}else{
    clearTable();
    Connection conn;
    //ResultSet rs;
    Statement st;
            try {
            String name=j3.getText();
            String Phone=j4.getText();
            int ppl=Integer.parseInt(j5.getText());
            int id1=Integer.parseInt(j6.getText());
            int id2=Integer.parseInt(j7.getText());
            int id3=Integer.parseInt(j8.getText());
            int id4=Integer.parseInt(j9.getText());
            int id5=Integer.parseInt(j10.getText());
            
            
          
            Class<?> clazz = Class.forName("oracle.jdbc.driver.OracleDriver"); Driver driver = (Driver) clazz.newInstance(); DriverManager.registerDriver(driver);
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "jr_new", "root");
            st = conn.createStatement();

st.executeQuery("insert into book(customer_id,c_name,c_ph,ppl_num,Activity1,Activity2,Activity3,Activity4,Activity5)values"
                   + "(seq_person.nextval,'"+name+"','"+Phone+"','"+ppl+"','"+id1+"','"+id2+"','"+id3+"','"+id4+"','"+id5+"')");
            
            conn.close();
            JOptionPane.showMessageDialog(this, "successfully inserted",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);// TODO add your handling code here:
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
System.out.print(e);            
        }
}
}
    public void clearTable(){
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    }
    public home_page() {
        initComponents();
    }
    public void clear(){
        j3.setText("");
        j4.setText("");
        j5.setText("");
        j6.setText("");
        j7.setText("");
        j8.setText("");
        j9.setText("");
    }
    public void display(){
        Connection conn;
    ResultSet rs;
    Statement st;
            try {
   
            Class<?> clazz = Class.forName("oracle.jdbc.driver.OracleDriver"); Driver driver = (Driver) clazz.newInstance(); DriverManager.registerDriver(driver);
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "jr_new", "root");
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM JR_NEW.ALL_ACTIVITIES order by Activity_id");
            while (rs.next()) {
                String id=String.valueOf(rs.getInt("Activity_id"));
                String name=rs.getString("name");
                String type=rs.getString("type");
                String exprience=rs.getString("exprience");
                
                String tbdata[]={id,name,type,exprience};
                DefaultTableModel tblModel =(DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbdata);
            
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        j10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        j9 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        j3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        j4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        j5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home_page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("show menu");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 110, 30));

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Activity_id", "name", "type", "exprience"
            }
        ));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 540, 230));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sand, Surf & Sun");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 220, 50));

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 110, 30));

        jButton6.setText("clearTable");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 100, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setText("Book");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));
        jPanel1.add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 71, -1));

        jLabel3.setText("Activity_1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 84, 22));

        jLabel4.setText("Activity_2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 84, 22));

        jLabel5.setText("Activity_3");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 84, 22));

        jLabel6.setText("Activity_4");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 84, 22));

        jLabel8.setText("Activity_5");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 84, 22));
        jPanel1.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 71, -1));
        jPanel1.add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 71, -1));
        jPanel1.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 71, -1));
        jPanel1.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 71, -1));

        jLabel11.setText("customer name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 20));
        jPanel1.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 100, 30));

        jLabel12.setText("Phone number");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, 20));

        j4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j4ActionPerformed(evt);
            }
        });
        jPanel1.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 100, 30));

        jLabel9.setText("number of people");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, 20));
        jPanel1.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, 30));

        jButton7.setText("clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 420, 290));

        jButton9.setText("on_beach");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton3.setText("under_water");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setText("in Air");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton2.setText("Instructor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 380, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_data/e832c18e-21ff-476a-b814-f5e96b52cabd-1-2.jpeg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Connection conn;
    ResultSet rs;
    Statement st;
            try {
   
            Class<?> clazz = Class.forName("oracle.jdbc.driver.OracleDriver"); Driver driver = (Driver) clazz.newInstance(); DriverManager.registerDriver(driver);
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "jr_new", "root");
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM JR_NEW.ALL_ACTIVITIES order by Activity_id");
            while (rs.next()) {
                String id=String.valueOf(rs.getInt("Activity_id"));
                String name=rs.getString("name");
                String type=rs.getString("type");
                String exprience=rs.getString("exprience");
                
                String tbdata[]={id,name,type,exprience};
                DefaultTableModel tblModel =(DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbdata);
            
            }
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        under_water u=new under_water();
        u.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
clearTable();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
on_air a=new on_air();
a.show();
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
on_beach b=new on_beach();
        b.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Instructor i=new Instructor();
        i.show();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Connection conn;
    ResultSet rs;
    Statement st;
            try {
   
            Class<?> clazz = Class.forName("oracle.jdbc.driver.OracleDriver"); Driver driver = (Driver) clazz.newInstance(); DriverManager.registerDriver(driver);
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "jr_new", "root");
            st = conn.createStatement();
            st.executeQuery("INSERT INTO all_activities (activity_id, Name,type,exprience)  (SELECT activity_id, Name,type,exprience from on_beach  UNION ALL   SELECT activity_id, Name,type,exprience from above_water  UNION ALL  SELECT activity_id, Name,type,exprience from under_water) MINUS (select * from all_activities)");
            st.executeQuery("delete from all_activities where activity_id in ((select activity_id from all_activities) MINUS (SELECT activity_id from on_beach  UNION ALL   SELECT activity_id from above_water  UNION ALL  SELECT activity_id from under_water) )");
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }  
            clearTable();
display();// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        //insertTable();
        if(j3.getText().equals("")){
    JOptionPane.showMessageDialog(this, "enter customer name to insert and select activity from table",
                                   "check for input", JOptionPane.OK_OPTION);
}else{
    clearTable();
    Connection conn;
    //ResultSet rs;
    Statement st;
            try {
            String name=j3.getText();
            String Phone=j4.getText();
            int ppl=Integer.parseInt(j5.getText());
            int id1=Integer.parseInt(j6.getText());
            int id2=Integer.parseInt(j7.getText());
            int id3=Integer.parseInt(j8.getText());
            int id4=Integer.parseInt(j9.getText());
            int id5=Integer.parseInt(j10.getText());
            
            
          
            Class<?> clazz = Class.forName("oracle.jdbc.driver.OracleDriver"); Driver driver = (Driver) clazz.newInstance(); DriverManager.registerDriver(driver);
            Class.forName("oracle.jdbc.driver.OracleDriver");
            conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "jr_new", "root");
            st = conn.createStatement();

st.executeQuery("insert into book(customer_id,c_name,c_ph,ppl_num,Activity1,Activity2,Activity3,Activity4,Activity5)values"
                   + "(seq_person.nextval,'"+name+"','"+Phone+"','"+ppl+"','"+id1+"','"+id2+"','"+id3+"','"+id4+"','"+id5+"')");
            
            conn.close();
            JOptionPane.showMessageDialog(this, "successfully inserted",
                                   "ERROR", JOptionPane.ERROR_MESSAGE);// TODO add your handling code here:
            clear();
            book b=new book();
            b.show();
            this.dispose();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
System.out.print(e);            
        }
}
        
        
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void j4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        al.add(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        ArrayList<String> l=new ArrayList<>(al);
        switch(l.size()){
            case 1:j6.setText(l.get(l.size()-1));
                    count++;
                    break;
            case 2:j7.setText(l.get(l.size()-1));
                    break;
            case 3:j8.setText(l.get(l.size()-1));
                    break;
            case 4:j9.setText(l.get(l.size()-1));
                    break;
            case 5:j10.setText(l.get(l.size()-1));
                    break;
            default : JOptionPane.showMessageDialog(this, "can select only five activities try clear" ,
                                   "ERROR", JOptionPane.ERROR_MESSAGE);
                                   count = 1;
        }
            
                    // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
       clear();
       home_page h=new home_page();
       h.show();
       this.dispose();
       count = 1;
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
